[2025-09-04T18:06:07.856+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T18:06:07.863+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T12:19:56.730327+00:00 [queued]>
[2025-09-04T18:06:07.866+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T12:19:56.730327+00:00 [queued]>
[2025-09-04T18:06:07.866+0545] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-09-04T18:06:07.878+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_mlflow> on 2025-09-04 12:19:56.730327+00:00
[2025-09-04T18:06:07.885+0545] {standard_task_runner.py:72} INFO - Started process 140835 to run task
[2025-09-04T18:06:07.889+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'start_diabetes_stack', 'start_mlflow', 'manual__2025-09-04T12:19:56.730327+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpkgng2ldr']
[2025-09-04T18:06:07.889+0545] {standard_task_runner.py:105} INFO - Job 280: Subtask start_mlflow
[2025-09-04T18:06:07.915+0545] {task_command.py:467} INFO - Running <TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-04T12:19:56.730327+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T18:06:07.938+0545] {abstractoperator.py:783} ERROR - Exception rendering Jinja template for task 'start_mlflow', field 'bash_command'. Template: 'bash /home/ashok/start_mlflow.sh'
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'bash /home/ashok/start_mlflow.sh' not found in search path: '/home/ashok/mlops_project/airflow/dags'
[2025-09-04T18:06:07.939+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'bash /home/ashok/start_mlflow.sh' not found in search path: '/home/ashok/mlops_project/airflow/dags'
[2025-09-04T18:06:07.941+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-04T18:06:07.941+0545] {logging_mixin.py:190} INFO - Task start:2025-09-04 12:21:07.863325+00:00 end:2025-09-04 12:21:07.941196+00:00 duration:0.077871
[2025-09-04T18:06:07.941+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_mlflow> dag:<DAG: start_diabetes_stack> dagrun:<DagRun start_diabetes_stack @ 2025-09-04 12:19:56.730327+00:00: manual__2025-09-04T12:19:56.730327+00:00, state:running, queued_at: 2025-09-04 12:19:56.740648+00:00. externally triggered: True>
[2025-09-04T18:06:07.941+0545] {logging_mixin.py:190} INFO - Failure caused by 'bash /home/ashok/start_mlflow.sh' not found in search path: '/home/ashok/mlops_project/airflow/dags'
[2025-09-04T18:06:07.941+0545] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=start_diabetes_stack, task_id=start_mlflow, run_id=manual__2025-09-04T12:19:56.730327+00:00, execution_date=20250904T121956, start_date=20250904T122107, end_date=20250904T122107
[2025-09-04T18:06:07.959+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T18:06:07.960+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 280 for task start_mlflow ('bash /home/ashok/start_mlflow.sh' not found in search path: '/home/ashok/mlops_project/airflow/dags'; 140835)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'bash /home/ashok/start_mlflow.sh' not found in search path: '/home/ashok/mlops_project/airflow/dags'
[2025-09-04T18:06:07.981+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-04T18:06:07.988+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T18:06:07.989+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
