[2025-09-04T10:06:18.637+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T10:06:18.644+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.create_predictions_table manual__2025-09-04T04:18:16.933841+00:00 [queued]>
[2025-09-04T10:06:18.648+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.create_predictions_table manual__2025-09-04T04:18:16.933841+00:00 [queued]>
[2025-09-04T10:06:18.648+0545] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-09-04T10:06:18.662+0545] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_predictions_table> on 2025-09-04 04:18:16.933841+00:00
[2025-09-04T10:06:18.674+0545] {standard_task_runner.py:72} INFO - Started process 38042 to run task
[2025-09-04T10:06:18.678+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mlops_diabetes_pipeline', 'create_predictions_table', 'manual__2025-09-04T04:18:16.933841+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/mlops_diabetes_pipeline.py', '--cfg-path', '/tmp/tmpi4wwzffp']
[2025-09-04T10:06:18.679+0545] {standard_task_runner.py:105} INFO - Job 47: Subtask create_predictions_table
[2025-09-04T10:06:18.710+0545] {task_command.py:467} INFO - Running <TaskInstance: mlops_diabetes_pipeline.create_predictions_table manual__2025-09-04T04:18:16.933841+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T10:06:18.749+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='koiralaashok02@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mlops_diabetes_pipeline' AIRFLOW_CTX_TASK_ID='create_predictions_table' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T04:18:16.933841+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T04:18:16.933841+00:00'
[2025-09-04T10:06:18.750+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-04T10:06:18.750+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-04T10:06:18.750+0545] {logging_mixin.py:190} INFO - Current task name:create_predictions_table state:running start_date:2025-09-04 04:21:18.644937+00:00
[2025-09-04T10:06:18.750+0545] {logging_mixin.py:190} INFO - Dag name:mlops_diabetes_pipeline and current dag run status:running
[2025-09-04T10:06:18.750+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-04T10:06:18.751+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py", line 504, in create_predictions_table
    with engine.begin() as conn:
NameError: name 'engine' is not defined
[2025-09-04T10:06:18.754+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-04T10:06:18.754+0545] {logging_mixin.py:190} INFO - Task start:2025-09-04 04:21:18.644937+00:00 end:2025-09-04 04:21:18.753989+00:00 duration:0.109052
[2025-09-04T10:06:18.754+0545] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_predictions_table> dag:<DAG: mlops_diabetes_pipeline> dagrun:<DagRun mlops_diabetes_pipeline @ 2025-09-04 04:18:16.933841+00:00: manual__2025-09-04T04:18:16.933841+00:00, state:running, queued_at: 2025-09-04 04:18:16.967837+00:00. externally triggered: True>
[2025-09-04T10:06:18.754+0545] {logging_mixin.py:190} INFO - Failure caused by name 'engine' is not defined
[2025-09-04T10:06:18.754+0545] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=mlops_diabetes_pipeline, task_id=create_predictions_table, run_id=manual__2025-09-04T04:18:16.933841+00:00, execution_date=20250904T041816, start_date=20250904T042118, end_date=20250904T042118
[2025-09-04T10:06:18.762+0545] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-09-04T10:06:18.763+0545] {email.py:272} INFO - Email alerting: attempt 1
[2025-09-04T10:06:22.634+0545] {email.py:283} INFO - Sent an alert email to ['koiralaashok02@gmail.com']
[2025-09-04T10:06:25.465+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T10:06:25.466+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task create_predictions_table (name 'engine' is not defined; 38042)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py", line 504, in create_predictions_table
    with engine.begin() as conn:
NameError: name 'engine' is not defined
[2025-09-04T10:06:25.519+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-04T10:06:25.548+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T10:06:25.562+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
